//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:25:49 PM CEST 
//


package https.developers_google_com.blockly.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;choice maxOccurs="unbounded" minOccurs="0"&amp;gt;
 *         &amp;lt;element ref="{https://developers.google.com/blockly/xml}category"/&amp;gt;
 *         &amp;lt;element ref="{https://developers.google.com/blockly/xml}sep"/&amp;gt;
 *         &amp;lt;element ref="{https://developers.google.com/blockly/xml}label"/&amp;gt;
 *         &amp;lt;element ref="{https://developers.google.com/blockly/xml}button"/&amp;gt;
 *         &amp;lt;element ref="{https://developers.google.com/blockly/xml}block"/&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *       &amp;lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="expanded" type="{http://www.w3.org/2001/XMLSchema}boolean" /&amp;gt;
 *       &amp;lt;attribute name="colour" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="categorystyle" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *       &amp;lt;attribute name="custom" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "categoryOrSepOrLabel"
})
@XmlRootElement(name = "category")
public class Category {

    @XmlElements({
        @XmlElement(name = "category", type = Category.class),
        @XmlElement(name = "sep", type = Sep.class),
        @XmlElement(name = "label", type = Label.class),
        @XmlElement(name = "button", type = Button.class),
        @XmlElement(name = "block", type = BlockType.class)
    })
    protected List<Object> categoryOrSepOrLabel;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "expanded")
    protected Boolean expanded;
    @XmlAttribute(name = "colour")
    @XmlSchemaType(name = "anySimpleType")
    protected String colour;
    @XmlAttribute(name = "categorystyle")
    @XmlSchemaType(name = "anySimpleType")
    protected String categorystyle;
    @XmlAttribute(name = "custom")
    @XmlSchemaType(name = "anySimpleType")
    protected String custom;

    /**
     * Gets the value of the categoryOrSepOrLabel property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the categoryOrSepOrLabel property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getCategoryOrSepOrLabel().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Category }
     * {@link Sep }
     * {@link Label }
     * {@link Button }
     * {@link BlockType }
     * 
     * 
     */
    public List<Object> getCategoryOrSepOrLabel() {
        if (categoryOrSepOrLabel == null) {
            categoryOrSepOrLabel = new ArrayList<Object>();
        }
        return this.categoryOrSepOrLabel;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the expanded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExpanded() {
        return expanded;
    }

    /**
     * Sets the value of the expanded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExpanded(Boolean value) {
        this.expanded = value;
    }

    /**
     * Gets the value of the colour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColour(String value) {
        this.colour = value;
    }

    /**
     * Gets the value of the categorystyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategorystyle() {
        return categorystyle;
    }

    /**
     * Sets the value of the categorystyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategorystyle(String value) {
        this.categorystyle = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom(String value) {
        this.custom = value;
    }

}
