//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.13 at 12:25:49 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://developers.google.com/blockly/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.developers_google_com.blockly.xml;
